# Generated by Django 6.0.1 on 2026-01-30 12:26

import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('position', models.CharField(choices=[('top_master', 'Top Master'), ('master', 'Master'), ('trainee', 'Trainee')], default='master', verbose_name='Позиция')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('telegramm', models.URLField(blank=True, null=True, verbose_name='Телеграмм')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Инстаграм')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='Тик Ток')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ваттсап')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Ютуб')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Оценка')),
                ('comment', models.TextField(max_length=1500, verbose_name='Комментарий')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(to='main.service', verbose_name='сервисы'),
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('comment', models.TextField(max_length=1500, verbose_name='Комментарий')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.master', verbose_name='Мастер')),
                ('services', models.ManyToManyField(to='main.service', verbose_name='сервисы')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('master', models.ManyToManyField(to='main.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Тип сервиса',
                'verbose_name_plural': 'Типы сервесов',
            },
        ),
    ]
