# Generated by Django 6.0.1 on 2026-01-31 15:59

import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('position', models.CharField(choices=[('top_master', 'Top Master'), ('master', 'Master'), ('trainee', 'Trainee')], default='master', max_length=20, verbose_name='Позиция')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('telegramm', models.URLField(blank=True, null=True, verbose_name='Телеграм')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Инстаграм')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('masters', models.ManyToManyField(related_name='services', to='main.master', verbose_name='Мастера')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.typeofservice', verbose_name='Тип сервиса')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('comment', models.TextField(blank=True, max_length=1500, verbose_name='Комментарий')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='main.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typeofservice', verbose_name='Тип сервиса')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
