# Generated by Django 6.0.1 on 2026-01-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.IntegerField(max_length=50, verbose_name='Опыт'),
        ),
    ]
