# Generated by Django 6.0.1 on 2026-01-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_master_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.typeofservice', verbose_name='Тип сервиса'),
            preserve_default=False,
        ),
    ]
